name: vibe_in
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter  
  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.14.3
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  flutter_bloc: ^9.1.1
  cloud_firestore: ^5.6.7
  firebase_storage: ^12.4.5
  file_picker: ^10.1.2
  cached_network_image: ^3.4.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  image_path_android: "assets/images/ic_launcher.png"
  image_path_ios: "assets/images/ic_launcher.png"
  android: true 
  ios: true 
  min_sdk_android: 21 
  remove_alpha_ios: true
  background_color_ios: "#28174A"
  adaptive_icon_background: "#28174A"
  adaptive_icon_foreground: "assets/images/ic_launcher.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/